"""
analyzer.py — LLM-powered process analysis using the Anthropic Claude API.
Takes parsed process statistics or plain text and returns a structured report.
"""

import anthropic
import os
from parser import format_stats_for_llm

MODEL = "claude-opus-4-6"

SYSTEM_PROMPT = """You are an expert business process analyst with 15+ years of experience in
process mining, operational excellence, and enterprise workflow optimization.
You analyze business process data and deliver clear, actionable insights that
help organizations reduce costs, eliminate bottlenecks, and improve throughput.

Your analysis style is:
- Direct and specific — no vague advice
- Data-driven — reference the actual numbers provided
- Prioritized — rank findings by business impact
- Practical — suggestions must be implementable by a mid-size company

Always structure your output in clean Markdown."""

ANALYSIS_PROMPT_CSV = """Analyze the following business process event log statistics and produce a comprehensive process audit report.

{stats_text}

---

Produce a structured report with these sections:

# Process Audit Report

## Executive Summary
2-3 sentence overview of the process health and the single most important finding.

## Key Metrics
A summary table of the critical numbers (cycle time, throughput, rework rate, etc.)

## Bottlenecks Identified
For each bottleneck: what it is, where it appears in the data, and its business impact.

## Inefficiencies & Waste
List specific inefficiencies found (rework loops, idle time, resource overload, etc.) with supporting data.

## Root Cause Analysis
For the top 2-3 issues: likely root causes based on the patterns in the data.

## Prioritized Recommendations
Numbered list, highest ROI first. For each:
- What to do
- Expected impact
- Effort to implement (Low / Medium / High)

## Quick Wins (Do This Week)
2-3 immediate actions that require no major investment.

---
*Report generated by AI Business Process Analyzer*"""

ANALYSIS_PROMPT_TEXT = """Analyze the following business process description and produce a comprehensive process audit report.

**Process Description:**
{process_description}

---

Based on this description, produce a structured report with these sections:

# Process Audit Report

## Executive Summary
2-3 sentence overview of the process and its likely pain points.

## Likely Bottlenecks
Based on the process description, identify where delays and bottlenecks are most likely to occur and why.

## Common Inefficiencies
Identify patterns of waste typical in this type of process (rework, waiting, handoff delays, manual steps, etc.)

## Root Cause Analysis
For the top 2-3 likely issues: root causes and contributing factors.

## Prioritized Recommendations
Numbered list, highest ROI first. For each:
- What to do
- Expected impact
- Effort to implement (Low / Medium / High)

## Process Improvement Roadmap
A phased 3-step improvement plan (Quick wins → Short-term → Strategic).

## Questions to Investigate
5 data-driven questions the business should answer to validate these findings with real process data.

---
*Report generated by AI Business Process Analyzer*"""


def analyze_from_stats(stats: dict, process_name: str = "Business Process") -> str:
    """
    Analyze parsed event log statistics and return a markdown report.

    Args:
        stats: Output from parser.parse_event_log()
        process_name: Human-readable name for the process

    Returns:
        Markdown report string
    """
    stats_text = f"**Process:** {process_name}\n\n" + format_stats_for_llm(stats)
    prompt = ANALYSIS_PROMPT_CSV.format(stats_text=stats_text)
    return _call_claude(prompt)


def analyze_from_text(process_description: str) -> str:
    """
    Analyze a plain-text process description and return a markdown report.

    Args:
        process_description: Free-text description of the process

    Returns:
        Markdown report string
    """
    prompt = ANALYSIS_PROMPT_TEXT.format(process_description=process_description)
    return _call_claude(prompt)


def _call_claude(prompt: str) -> str:
    """Make the API call to Claude and return the response text."""
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY not set. Add it to your .env file or environment variables."
        )

    client = anthropic.Anthropic(api_key=api_key)

    message = client.messages.create(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}],
    )

    return message.content[0].text
